version: '3.8'

services:
  backend:
    build: ./BE
    ports:
      - "8080:8080"
    environment:
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

      - jwt.secret=${JWT_SECRET}
      - fcm.service-account-key-path=${FCM_SECRET}

      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - INCIZORLENS_API_KEY=${INCIZORLENS_API_KEY}
      - INCIZORLENS_API_URL=${INCIZORLENS_API_URL}
      - NAVER_OCR_API_URL=${NAVER_OCR_API_URL}
      - NAVER_OCR_SECRET_KEY=${NAVER_OCR_SECRET_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}